const SUBJECTS = {
  maths:{name:'Maths',icon:'➗',skills:['Place value','Addition & subtraction','Multiplication & division','Fractions','Decimals','Money','Time','Measurement','Geometry','Statistics']},
  english:{name:'English',icon:'📚',skills:['Reading','Vocabulary','Spelling','Grammar','Punctuation','Writing','Common/proper/abstract nouns','Verbs & tenses','Adjectives & adverbs','Comprehension']},
  science:{name:'Science',icon:'🔬',skills:['Living things','Animals including humans','States of matter','Sound','Electricity','Working scientifically']},
  computing:{name:'Computing',icon:'💻',skills:['Algorithms','Programming','Debugging','Networks','Internet','Data','Digital safety']},
  geography:{name:'Geography',icon:'🌍',skills:['UK geography','Europe','World geography','Maps','Rivers','Mountains','Settlements','Climate']},
  history:{name:'History',icon:'🏺',skills:['Chronology','Romans','Anglo-Saxons','Vikings','Ancient civilisations','Evidence & sources']},
  french:{name:'French',icon:'🇫🇷',skills:['Greetings','Numbers','Colours','Family','School','Food','Days & months','Simple sentences']},
  art:{name:'Art & Design',icon:'🎨',skills:['Drawing','Colour','Painting','Sculpture','Pattern','Artists','Evaluate & improve']},
  design:{name:'Design & Technology',icon:'🛠️',skills:['Design','Make','Evaluate','Structures','Mechanisms','Food & nutrition','Materials']},
  music:{name:'Music',icon:'🎵',skills:['Pulse','Rhythm','Pitch','Notation','Instruments','Listening','Composition']},
  pe:{name:'PE & Health',icon:'🏃',skills:['Movement','Coordination','Games','Fitness','Swimming safety','Healthy habits']},
  life:{name:'Life Skills',icon:'🧠',skills:['Money sense','Safety','Communication','Problem solving','Emotions','Organisation','Digital citizenship','Critical thinking']}
};

const FACTS = {
  science:[
    ['solid','keeps its own shape'],['liquid','flows and takes the shape of its container'],['gas','spreads to fill its container'],
    ['evaporation','liquid changing into gas'],['condensation','gas changing into liquid'],['freezing','liquid changing into solid'],
    ['melting','solid changing into liquid'],['vibration','a back-and-forth movement that can make sound'],['pitch','how high or low a sound is'],
    ['volume','how loud or quiet a sound is'],['circuit','a complete path for electric current'],['conductor','a material that lets electricity pass through it'],
    ['insulator','a material that does not easily let electricity pass through it'],['producer','a living thing that makes its own food'],
    ['vertebrate','an animal with a backbone'],['invertebrate','an animal without a backbone'],['habitat','the place where an organism lives'],
    ['digestive system','the organs that break down food and absorb nutrients'],['incisor','a front tooth used for cutting'],['molar','a back tooth used for crushing and grinding']
  ],
  computing:[
    ['algorithm','a precise set of steps for solving a problem'],['program','instructions a computer can follow'],['debug','find and fix errors in a program'],
    ['sequence','instructions carried out in order'],['loop','instructions that repeat'],['variable','a named place for storing a value'],
    ['network','connected devices that can communicate'],['internet','a worldwide network of networks'],['browser','software used to view websites'],
    ['search engine','a service that helps find information online'],['password','a secret used to protect an account'],['phishing','a trick that tries to steal personal information'],
    ['personal information','information that can identify you'],['data','information stored or processed by a computer'],['input','information sent into a computer system'],
    ['output','information produced by a computer system'],['sprite','a programmable character or object'],['event','an action that can trigger code'],
    ['decomposition','breaking a big problem into smaller parts'],['pattern','something that repeats or follows a rule']
  ],
  geography:[
    ['England','London'],['Scotland','Edinburgh'],['Wales','Cardiff'],['Northern Ireland','Belfast'],['France','Paris'],['Spain','Madrid'],['Italy','Rome'],['Germany','Berlin'],
    ['river source','where a river begins'],['river mouth','where a river enters a sea, lake or another river'],['tributary','a smaller river that joins a larger one'],
    ['equator','an imaginary line halfway between the North and South Poles'],['latitude','lines measuring distance north or south of the Equator'],['longitude','lines measuring distance east or west'],
    ['urban','relating to towns and cities'],['rural','relating to the countryside'],['settlement','a place where people live'],['climate','usual weather conditions over a long period'],
    ['mountain','a high natural area of land'],['contour line','a map line joining places of equal height']
  ],
  history:[
    ['chronology','putting events in time order'],['primary source','evidence created at the time being studied'],['secondary source','an account made later using other evidence'],
    ['Roman Empire','a large empire centred on Rome'],['emperor','a ruler of an empire'],['legion','a large unit of Roman soldiers'],['aqueduct','a structure built to carry water'],
    ['Anglo-Saxons','groups who settled in Britain after Roman rule'],['Vikings','seafaring people from Scandinavia'],['longship','a fast Viking ship'],
    ['archaeology','learning about the past from objects and sites'],['artefact','an object made or used by people in the past'],['invasion','entering a country by force'],
    ['settlement','a place where people establish a community'],['monastery','a community where monks or nuns live'],['kingdom','land ruled by a king or queen'],
    ['Boudica','a queen who led a revolt against Roman rule'],['Hadrian’s Wall','a Roman frontier built across northern Britain'],['AD 43','the year the Roman invasion of Britain began under Claudius'],['1066','the year of the Norman Conquest']
  ],
  art:[['primary colours','red, yellow and blue'],['secondary colours','colours made by mixing two primary colours'],['tone','how light or dark a colour is'],['texture','how a surface feels or looks as if it feels'],['pattern','a repeated visual design'],['composition','how visual elements are arranged'],['sketch','a quick drawing used to explore an idea'],['sculpture','three-dimensional artwork'],['portrait','art showing a person'],['landscape','art showing scenery']],
  design:[['prototype','an early model used to test an idea'],['evaluate','judge what works and what could improve'],['criteria','requirements a design should meet'],['structure','parts joined together to support a load'],['mechanism','parts that work together to create movement'],['lever','a rigid bar that turns around a pivot'],['linkage','connected parts that transfer movement'],['nutrition','how food supports health and growth'],['hygiene','practices that keep people and food clean'],['user','the person a product is designed for']],
  music:[['pulse','the steady beat in music'],['rhythm','a pattern of long and short sounds'],['pitch','how high or low a note sounds'],['tempo','the speed of music'],['dynamics','how loud or quiet music is'],['melody','a sequence of notes that forms a tune'],['harmony','notes sounding together'],['rest','a period of silence in music'],['bar','a group of beats'],['composer','a person who creates music']],
  pe:[['warm-up','activity that prepares the body for exercise'],['cool-down','gentle activity after exercise'],['stamina','ability to keep going during activity'],['coordination','using body parts together smoothly'],['balance','staying controlled and steady'],['hydration','having enough water in the body'],['fair play','following rules and treating others respectfully'],['teamwork','working effectively with other people'],['heart rate','how many times the heart beats per minute'],['recovery','time and actions that help the body return to normal after exercise']],
  life:[['budget','a plan for how money will be used'],['need','something essential'],['want','something desirable but not essential'],['saving','keeping money for future use'],['empathy','understanding how another person may feel'],['assertive','clear and respectful about your needs or boundaries'],['priority','something important that should be done first'],['risk','the chance that something harmful could happen'],['evidence','information that supports a conclusion'],['reliable source','a source that can reasonably be trusted']]
};

const FRENCH = [['bonjour','hello'],['au revoir','goodbye'],['merci','thank you'],['s’il vous plaît','please'],['un','one'],['deux','two'],['trois','three'],['quatre','four'],['cinq','five'],['rouge','red'],['bleu','blue'],['vert','green'],['jaune','yellow'],['mère','mother'],['père','father'],['frère','brother'],['sœur','sister'],['lundi','Monday'],['mardi','Tuesday'],['mercredi','Wednesday'],['jeudi','Thursday'],['vendredi','Friday'],['école','school'],['livre','book'],['pomme','apple'],['eau','water']];

const ENGLISH_WORDS={common:['teacher','bicycle','river','school','pencil','doctor','mountain','book','friend','city','dog','table'],proper:['London','Friday','Paris','Matilda','Scotland','April','Wednesday','Thames','Manchester','Amazon'],abstract:['kindness','happiness','fear','friendship','bravery','honesty','anger','joy','freedom','confidence','patience','excitement']};

const STORE='ks2genius-v1';
const today=()=>new Date().toISOString().slice(0,10);
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a};
const pick=a=>a[Math.floor(Math.random()*a.length)];
const uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);

function defaultState(){return {childName:'Learner',xp:0,streakDays:0,lastDay:null,mastery:{},attempts:[],daily:{},settings:{dailyLevels:4,dailyMinutes:35,aiTutor:true},parentPin:'2468'};}
function loadState(){try{return {...defaultState(),...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{return defaultState()}}
function saveState(){localStorage.setItem(STORE,JSON.stringify(app.state));}
function key(subject,skill){return `${subject}:${skill}`}
function mastery(subject,skill){return app.state.mastery[key(subject,skill)]??45}
function recordAttempt(q,chosen,correct){const k=key(q.subject,q.skill);const old=mastery(q.subject,q.skill);const difficulty=q.difficulty||1;const gain=correct?(3+difficulty):( -Math.max(2,difficulty));app.state.mastery[k]=clamp(old+gain,0,100);app.state.attempts.push({id:uid(),at:Date.now(),subject:q.subject,skill:q.skill,question:q.prompt,chosen,answer:q.answer,correct});app.state.attempts=app.state.attempts.slice(-1500);if(correct)app.state.xp+=10+difficulty*2;saveState();}

function ensureDaily(){const d=today();if(app.state.daily.date===d)return;const weak=allSkillRows().sort((a,b)=>a.mastery-b.mastery);const priority=weak.slice(0,3).map(x=>x.subject);const core=['maths','english','science'];const subjects=[...new Set([...priority,...core,...shuffle(Object.keys(SUBJECTS))])].slice(0,app.state.settings.dailyLevels);app.state.daily={date:d,subjects,done:[],target:subjects.length};if(app.state.lastDay){const diff=(new Date(d)-new Date(app.state.lastDay))/86400000;app.state.streakDays=diff===1?app.state.streakDays+1:diff>1?1:app.state.streakDays;}else app.state.streakDays=1;app.state.lastDay=d;saveState();}
function allSkillRows(){return Object.entries(SUBJECTS).flatMap(([subject,s])=>s.skills.map(skill=>({subject,skill,mastery:mastery(subject,skill)})));}
function weakSkills(limit=6){return allSkillRows().sort((a,b)=>a.mastery-b.mastery).slice(0,limit)}
function subjectMastery(subject){const skills=SUBJECTS[subject].skills;return Math.round(skills.reduce((n,s)=>n+mastery(subject,s),0)/skills.length)}
function nextDailySubject(){ensureDaily();return app.state.daily.subjects.find(s=>!app.state.daily.done.includes(s))||null;}

function choiceQuestion(subject,skill,prompt,answer,options,explain,difficulty=1){return {id:uid(),subject,skill,prompt,answer,choices:shuffle([...new Set([answer,...options])]).slice(0,4),explain,difficulty};}
function genMath(){const skills=SUBJECTS.maths.skills;const skill=pick(skills);let a,b,ans,prompt,opts=[];
  if(skill==='Place value'){a=Math.floor(Math.random()*9000)+1000;const p=pick([10,100,1000]);ans=Math.floor(a/p)%10;prompt=`What digit is in the ${p===10?'tens':p===100?'hundreds':'thousands'} place in ${a}?`;opts=[0,1,2,3,4,5,6,7,8,9].filter(x=>x!==ans);}
  else if(skill==='Addition & subtraction'){a=Math.floor(Math.random()*8000)+500;b=Math.floor(Math.random()*900)+50;const add=Math.random()>.45;ans=add?a+b:a-b;prompt=`${a} ${add?'+':'−'} ${b} = ?`;opts=[ans+10,ans-10,ans+100,ans-100];}
  else if(skill==='Multiplication & division'){a=Math.floor(Math.random()*12)+1;b=Math.floor(Math.random()*12)+1;const div=Math.random()>.55;ans=div?a:a*b;prompt=div?`${a*b} ÷ ${b} = ?`:`${a} × ${b} = ?`;opts=[ans+1,ans-1,ans+b,ans*2];}
  else if(skill==='Fractions'){const den=pick([2,3,4,5,8,10,12]);const num=Math.floor(Math.random()*den)+1;ans=`${num}/${den}`;prompt=`Which fraction means ${num} out of ${den} equal parts?`;opts=[`${den}/${num}`,`${Math.max(1,num-1)}/${den}`,`${num}/${den+1}`];}
  else if(skill==='Decimals'){a=Math.floor(Math.random()*90)+10;ans=(a/10).toFixed(1);prompt=`Write ${a}/10 as a decimal.`;opts=[String(a),`0.${a}`,`${Math.floor(a/10)}.${a%10+1}`];}
  else if(skill==='Money'){a=Math.floor(Math.random()*800)+100;b=Math.floor(Math.random()*a);ans=`£${((a-b)/100).toFixed(2)}`;prompt=`You have £${(a/100).toFixed(2)} and spend £${(b/100).toFixed(2)}. How much is left?`;opts=[`£${(a/100).toFixed(2)}`,`£${(b/100).toFixed(2)}`,`£${((a+b)/100).toFixed(2)}`];}
  else if(skill==='Time'){a=pick([15,30,45,60,90,120]);ans=`${a} minutes`;prompt=`How many minutes is ${a===60?'1 hour':a===90?'1 hour 30 minutes':a===120?'2 hours':a+' minutes'}?`;opts=[`${Math.max(5,a-15)} minutes`,`${a+15} minutes`,`${a*2} minutes`];}
  else if(skill==='Measurement'){a=Math.floor(Math.random()*9)+1;ans=`${a*100} cm`;prompt=`${a} metres equals how many centimetres?`;opts=[`${a*10} cm`,`${a*1000} cm`,`${a+100} cm`];}
  else if(skill==='Geometry'){const sides=pick([3,4,5,6,8]);const names={3:'triangle',4:'quadrilateral',5:'pentagon',6:'hexagon',8:'octagon'};ans=names[sides];prompt=`Which shape has ${sides} sides?`;opts=Object.values(names).filter(x=>x!==ans);}
  else {const vals=[2,3,4,5,6,7,8,9];a=pick(vals);b=pick(vals);ans=a+b;prompt=`A chart shows ${a} red books and ${b} blue books. How many books altogether?`;opts=[a,b,Math.abs(a-b),a+b+1];}
  return choiceQuestion('maths',skill,prompt,String(ans),opts.map(String),`This practises ${skill.toLowerCase()}.`,2);
}
function genEnglish(){const skill=pick(SUBJECTS.english.skills);if(skill==='Common/proper/abstract nouns'){const type=pick(['common','proper','abstract']);const word=pick(ENGLISH_WORDS[type]);return choiceQuestion('english',skill,`What type of noun is “${word}”?`,type[0].toUpperCase()+type.slice(1)+' noun',['Common noun','Proper noun','Abstract noun'],`${word} is a ${type} noun.`,1)}
  if(skill==='Punctuation'){const n=pick(['Maya','Daniel','Sophie']);const place=pick(['London','Paris','Scotland']);const correct=`${n} visited ${place}.`;return choiceQuestion('english',skill,'Which sentence is punctuated and capitalised correctly?',correct,[`${n.toLowerCase()} visited ${place}.`,`${n} visited ${place.toLowerCase()}.`,`${n} visited ${place}`],'Names need capital letters and a statement ends with a full stop.',2)}
  if(skill==='Verbs & tenses'){const v=pick([['walk','walked'],['jump','jumped'],['play','played'],['visit','visited']]);return choiceQuestion('english',skill,`Which word shows the past tense of “${v[0]}”?`,v[1],[v[0],v[0]+'ing','will '+v[0]],`${v[1]} shows the action already happened.`,2)}
  if(skill==='Adjectives & adverbs'){const ad=Math.random()>.5;return ad?choiceQuestion('english',skill,'Which word is an adjective in “The bright lantern glowed”?','bright',['lantern','glowed','the'],'An adjective describes a noun.',1):choiceQuestion('english',skill,'Which word is an adverb in “The fox moved quietly”?','quietly',['fox','moved','the'],'An adverb can describe how an action happens.',1)}
  if(skill==='Spelling'){const pair=pick([['because','becuase'],['different','diffrent'],['important','importent'],['remember','rember'],['separate','seperate']]);return choiceQuestion('english',skill,'Choose the correctly spelled word.',pair[0],[pair[1],pair[0]+'e',pair[0].slice(0,-1)],`The correct spelling is ${pair[0]}.`,2)}
  if(skill==='Vocabulary'){const pair=pick([['enormous','very large'],['ancient','very old'],['rapid','fast'],['fragile','easily broken'],['observe','watch carefully']]);return choiceQuestion('english',skill,`What does “${pair[0]}” mean?`,pair[1],['very small','very noisy','completely empty'],`${pair[0]} means ${pair[1]}.`,2)}
  const passage=pick([{t:'Lena packed a raincoat before walking to the park because dark clouds were gathering.',q:'Why did Lena pack a raincoat?',a:'Dark clouds suggested it might rain.'},{t:'Arun checked the timetable twice so he would not miss the train.',q:'Why did Arun check the timetable twice?',a:'He wanted to avoid missing the train.'},{t:'The puppy waited beside its empty bowl and wagged its tail when Mia entered.',q:'What can you infer?',a:'The puppy probably wanted food.'}]);return choiceQuestion('english',skill,`${passage.t}\n\n${passage.q}`,passage.a,['The character was bored.','The character wanted to sleep.','There is not enough information.'],'Use clues in the text to infer the most sensible answer.',3);
}
function genFactSubject(subject){const facts=FACTS[subject]||FACTS.life;const [term,meaning]=pick(facts);const wrong=shuffle(facts.filter(x=>x[0]!==term).map(x=>x[1])).slice(0,3);const skill=pick(SUBJECTS[subject].skills);return choiceQuestion(subject,skill,`Which description best matches “${term}”?`,meaning,wrong,`${term} means ${meaning}.`,2);}
function genFrench(){const [fr,en]=pick(FRENCH);const wrong=shuffle(FRENCH.filter(x=>x[0]!==fr).map(x=>x[1])).slice(0,3);return choiceQuestion('french',pick(SUBJECTS.french.skills),`What does “${fr}” mean?`,en,wrong,`${fr} means ${en}.`,1);}
function generateQuestion(subject){if(subject==='maths')return genMath();if(subject==='english')return genEnglish();if(subject==='french')return genFrench();return genFactSubject(subject);}

function chooseAdaptiveQuestion(subject){const skills=SUBJECTS[subject].skills;const weighted=[];skills.forEach(skill=>{const m=mastery(subject,skill);const weight=Math.max(1,Math.ceil((105-m)/15));for(let i=0;i<weight;i++)weighted.push(skill)});let q;for(let tries=0;tries<20;tries++){q=generateQuestion(subject);if(weighted.includes(q.skill)&&Math.random()<.8)break;}return q;}

const app={state:loadState(),current:null,level:null,answerLocked:false};
function qs(s){return document.querySelector(s)}
function qsa(s){return [...document.querySelectorAll(s)]}
function show(view){qsa('[data-view]').forEach(x=>x.hidden=x.dataset.view!==view);window.scrollTo({top:0,behavior:'smooth'});}
function subjectCard(id){const s=SUBJECTS[id],m=subjectMastery(id);return `<button class="subject-card" data-subject="${id}"><span class="subject-icon">${s.icon}</span><span><strong>${s.name}</strong><small>${m}% mastery</small></span><i style="--p:${m}%"></i></button>`}
function renderHome(){ensureDaily();qs('#childName').textContent=app.state.childName;qs('#xp').textContent=app.state.xp;qs('#streak').textContent=app.state.streakDays;const done=app.state.daily.done.length,total=app.state.daily.target;qs('#dailyProgress').textContent=`${done}/${total}`;qs('#dailyBar').style.width=`${total?done/total*100:100}%`;qs('#dailySubjects').innerHTML=app.state.daily.subjects.map(id=>`<span class="task-chip ${app.state.daily.done.includes(id)?'done':''}">${SUBJECTS[id].icon} ${SUBJECTS[id].name}</span>`).join('');const next=nextDailySubject();qs('#dailyStart').textContent=next?`Start ${SUBJECTS[next].name} mission`:'Daily mission complete 🎉';qs('#dailyStart').disabled=!next;qs('#subjects').innerHTML=Object.keys(SUBJECTS).map(subjectCard).join('');qs('#weakSkills').innerHTML=weakSkills(5).map(x=>`<li><span>${SUBJECTS[x.subject].icon} ${x.skill}</span><strong>${x.mastery}%</strong></li>`).join('');}
function startLevel(subject,{daily=false}={}){app.level={subject,daily,number:1,index:0,total:10,correct:0,review:[],build:0};show('play');renderPlayHeader();nextQuestion();}
function renderPlayHeader(){const s=SUBJECTS[app.level.subject];qs('#playSubject').textContent=`${s.icon} ${s.name}`;qs('#playProgressText').textContent=`Question ${app.level.index+1} of ${app.level.total}`;qs('#playBar').style.width=`${app.level.index/app.level.total*100}%`;renderBuild();}
function renderBuild(){const n=app.level.build;qs('#buildCount').textContent=`${n}/10 built`;qs('#buildPieces').innerHTML=Array.from({length:10},(_,i)=>`<span class="build-block ${i<n?'on':''}" style="--i:${i}"></span>`).join('');}
function nextQuestion(){if(app.level.index>=app.level.total)return finishLevel();app.answerLocked=false;app.current=chooseAdaptiveQuestion(app.level.subject);const q=app.current;qs('#skillLabel').textContent=q.skill;qs('#question').textContent=q.prompt;qs('#answers').innerHTML=q.choices.map(c=>`<button class="answer" data-answer="${encodeURIComponent(c)}">${c}</button>`).join('');qs('#feedback').hidden=true;qs('#nextQuestion').hidden=true;renderPlayHeader();}
function answer(choice){if(app.answerLocked)return;app.answerLocked=true;const q=app.current,correct=choice===q.answer;recordAttempt(q,choice,correct);app.level.review.push({...q,chosen:choice,correct});if(correct){app.level.correct++;app.level.build++;renderBuild();}qsa('.answer').forEach(b=>{const val=decodeURIComponent(b.dataset.answer);b.disabled=true;if(val===q.answer)b.classList.add('correct');if(val===choice&&!correct)b.classList.add('wrong');});qs('#feedback').hidden=false;qs('#feedback').className='feedback '+(correct?'good':'bad');qs('#feedback').innerHTML=`<strong>${correct?'✅ Correct!':'❌ Not quite'}</strong><p>${correct?q.explain:`Correct answer: <b>${q.answer}</b>. ${q.explain}`}</p>`;qs('#nextQuestion').hidden=false;qs('#playBar').style.width=`${(app.level.index+1)/app.level.total*100}%`;}
function advance(){app.level.index++;nextQuestion();}
function finishLevel(){if(app.level.daily&&!app.state.daily.done.includes(app.level.subject)){app.state.daily.done.push(app.level.subject);saveState();}renderReview();show('review');}
function renderReview(){const rows=app.level.review;qs('#reviewTitle').textContent=`${SUBJECTS[app.level.subject].name} Level Review`;qs('#reviewScore').textContent=`${app.level.correct}/10 correct`;qs('#reviewList').innerHTML=rows.map((r,i)=>`<article class="review-item ${r.correct?'right':'wrong'}"><header><span>${r.correct?'✅':'❌'}</span><strong>Question ${i+1}</strong><small>${r.skill}</small></header><p class="review-q">${r.prompt}</p><p>Your answer: <b>${r.chosen}</b></p>${r.correct?'':`<p>Correct answer: <b>${r.answer}</b></p>`}<p class="why">${r.explain}</p></article>`).join('');const weak=rows.filter(x=>!x.correct).map(x=>x.skill);qs('#reviewInsight').textContent=weak.length?`Focus next: ${[...new Set(weak)].slice(0,3).join(', ')}.`:'Perfect round. The next session will increase difficulty.';}
function continueAfterReview(){renderHome();show('home');}
function renderParent(){const rows=allSkillRows();const attempts=app.state.attempts;const last7=attempts.filter(a=>a.at>Date.now()-7*86400000);const accuracy=last7.length?Math.round(last7.filter(a=>a.correct).length/last7.length*100):0;qs('#parentChild').textContent=app.state.childName;qs('#parentAccuracy').textContent=accuracy+'%';qs('#parentQuestions').textContent=last7.length;qs('#parentXP').textContent=app.state.xp;qs('#parentSubjects').innerHTML=Object.entries(SUBJECTS).map(([id,s])=>{const m=subjectMastery(id);return `<div class="parent-row"><span>${s.icon} ${s.name}</span><div><i style="width:${m}%"></i></div><strong>${m}%</strong></div>`}).join('');qs('#parentWeak').innerHTML=weakSkills(8).map(x=>`<li>${SUBJECTS[x.subject].name} — ${x.skill}: <b>${x.mastery}%</b></li>`).join('');qs('#recentAttempts').innerHTML=attempts.slice(-12).reverse().map(a=>`<li class="${a.correct?'ok':'no'}"><span>${a.correct?'✅':'❌'} ${SUBJECTS[a.subject].name}</span><small>${a.skill}</small></li>`).join('');}
async function askTutor(){const input=qs('#tutorInput');const msg=input.value.trim();if(!msg)return;qs('#tutorReply').textContent='Thinking…';try{const weak=weakSkills(4);const res=await fetch('/api/tutor',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:msg,childName:app.state.childName,weakSkills:weak,year:4})});const data=await res.json().catch(()=>({}));if(!res.ok||data.mode==='unavailable'){qs('#tutorReply').textContent='AI tutor is unavailable right now. Try a subject mission instead.';return;}qs('#tutorReply').textContent=data.reply||'Tutor is unavailable right now.';}catch{qs('#tutorReply').textContent='AI tutor is unavailable right now. Try a subject mission instead.';}}
function install(){ensureDaily();renderHome();document.addEventListener('click',e=>{const subject=e.target.closest('[data-subject]');if(subject)return startLevel(subject.dataset.subject);if(e.target.closest('#dailyStart')){const s=nextDailySubject();if(s)startLevel(s,{daily:true});}if(e.target.closest('[data-nav="home"]')){renderHome();show('home')}if(e.target.closest('[data-nav="parent"]')){renderParent();show('parent')}if(e.target.closest('[data-nav="tutor"]'))show('tutor');if(e.target.closest('.answer'))answer(decodeURIComponent(e.target.closest('.answer').dataset.answer));if(e.target.closest('#nextQuestion'))advance();if(e.target.closest('#finishReview'))continueAfterReview();if(e.target.closest('#askTutor'))askTutor();});qs('#editName').addEventListener('click',()=>{const n=prompt('Child name',app.state.childName);if(n&&n.trim()){app.state.childName=n.trim().slice(0,24);saveState();renderHome();}});if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});}
window.addEventListener('DOMContentLoaded',install);
