(()=>{
const A='ks2genius-v1',W='ks2-world-v1',E='ks2-engagement-v1';
const read=(k,f={})=>{try{return {...f,...JSON.parse(localStorage.getItem(k)||'{}')}}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const today=()=>new Date().toISOString().slice(0,10);
const base=()=>({lastChest:null,chests:0,companion:'owl',unlockedCompanions:['owl'],cosmetic:'blue-pack',unlockedCosmetics:['blue-pack'],league:'Bronze',weekKey:'',friendCode:'',friends:[],familyGoal:500,familyProgress:0,parentReward:'',parentRewardTarget:4,parentRewardClaimed:false,access:{largeText:false,dyslexia:false,reducedMotion:false,highContrast:false,tts:false},secretFound:[],bossWins:0,miniWins:0});
let e=read(E,base());
const app=()=>read(A,{xp:0,streakDays:1,daily:{done:[],target:4},mastery:{},attempts:[],childName:'Learner'});
const world=()=>read(W,{coins:0,earned:0,spent:0});
function save(){write(E,e);applyAccess()}
function toast(t){let x=document.querySelector('.ga-toast');if(!x){x=document.createElement('div');x.className='ga-toast';document.body.append(x)}x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function award(n,label){const w=world();w.coins=(w.coins||0)+n;w.earned=(w.earned||0)+n;write(W,w);dispatchEvent(new Event('ks2coins'));toast(`🪙 +${n} ${label}`)}
const compName=id=>({owl:'Professor Hoot',fox:'Pixel Fox',robot:'Byte Bot',dragon:'Fraction Dragon',unicorn:'Nova Unicorn'})[id]||id;
const compIcon=id=>({owl:'🦉',fox:'🦊',robot:'🤖',dragon:'🐉',unicorn:'🦄'})[id]||'🦉';
const cosIcon=id=>({'blue-pack':'🎒','gold-cape':'🦸','star-boots':'🥾','crystal-trail':'✨',crown:'👑'})[id]||'🎒';
function mastery(sub){const vals=Object.entries(app().mastery||{}).filter(([k])=>k.startsWith(sub+':')).map(([,v])=>v);return vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length):45}
const stage=sub=>{const m=mastery(sub);return m>=85?4:m>=70?3:m>=55?2:1};
function season(){const m=new Date().getMonth()+1;return m<=2||m===12?['❄️','Winter Academy','Crystal trails and winter quests']:m<=5?['🌸','Spring Discovery','Garden secrets and science expeditions']:m<=8?['☀️','Summer Festival','Festival quests, exploration and bonus rewards']:['🍂','Autumn Adventure','Mystery trails and story challenges']}
function sync(){const a=app(),xp=a.xp||0;for(const [id,n] of [['owl',0],['fox',250],['robot',600],['dragon',1200],['unicorn',2200]])if(xp>=n&&!e.unlockedCompanions.includes(id)){e.unlockedCompanions.push(id);toast(`✨ ${compName(id)} unlocked!`)}for(const [id,n] of [['blue-pack',0],['gold-cape',400],['star-boots',900],['crystal-trail',1600],['crown',2600]])if(xp>=n&&!e.unlockedCosmetics.includes(id)){e.unlockedCosmetics.push(id);toast('🎒 New avatar item unlocked!')}e.league=xp>=2400?'Diamond':xp>=1500?'Gold':xp>=700?'Silver':'Bronze';e.familyProgress=Math.min(e.familyGoal,(a.attempts||[]).filter(x=>Date.now()-x.at<604800000&&x.correct).length);if(!e.friendCode)e.friendCode='GA'+Math.random().toString(36).slice(2,8).toUpperCase();save()}
function modal(title,html){let m=document.getElementById('gaModal');if(!m){m=document.createElement('div');m.id='gaModal';m.className='ga-modal';m.innerHTML='<div class="ga-sheet"><div class="ga-sheet-head"><h2 id="gaTitle"></h2><button class="ga-close">✕</button></div><div id="gaBody"></div></div>';document.body.append(m);m.querySelector('.ga-close').onclick=()=>m.hidden=true;m.onclick=x=>{if(x.target===m)m.hidden=true}}m.hidden=false;m.querySelector('#gaTitle').textContent=title;m.querySelector('#gaBody').innerHTML=html;return m}
function chest(){const a=app(),d=a.daily?.done?.length||0,t=a.daily?.target||4;if(d<t)return toast('Complete today’s quests first');if(e.lastChest===today())return toast('Chest already opened today');const n=[25,30,40,50][Math.floor(Math.random()*4)];e.lastChest=today();e.chests++;save();award(n,'Mystery Chest');modal('Mystery Chest!',`<div style="text-align:center;font-size:72px">🎁✨</div><h2 style="text-align:center">${n} KS2 Coins!</h2><p style="text-align:center">Complete tomorrow’s quest chain for another chest.</p>`)}
function companions(){const m=modal('Companion Collection',`<p>Earn companions by learning. Your selected companion explores the academy with you.</p><div class="ga-choice-grid">${e.unlockedCompanions.map(id=>`<button class="ga-choice ${e.companion===id?'selected':''}" data-c="${id}"><span class="big">${compIcon(id)}</span><strong>${compName(id)}</strong><small>${e.companion===id?'Following you':'Equip'}</small></button>`).join('')}</div>`);m.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{e.companion=b.dataset.c;save();dispatchEvent(new Event('ga-companion'));companions()})}
function wardrobe(){const names={'blue-pack':'Explorer Backpack','gold-cape':'Golden Cape','star-boots':'Star Boots','crystal-trail':'Crystal Trail',crown:'Academy Crown'},m=modal('Avatar Wardrobe',`<p>Cosmetics are earned through learning, not purchased.</p><div class="ga-choice-grid">${e.unlockedCosmetics.map(id=>`<button class="ga-choice ${e.cosmetic===id?'selected':''}" data-cos="${id}"><span class="big">${cosIcon(id)}</span><strong>${names[id]}</strong><small>${e.cosmetic===id?'Equipped':'Equip'}</small></button>`).join('')}</div>`);m.querySelectorAll('[data-cos]').forEach(b=>b.onclick=()=>{e.cosmetic=b.dataset.cos;save();wardrobe()})}
function boss(){const sub=['maths','english','science'][e.bossWins%3],name={maths:'Fraction Dragon',english:'Word Wizard',science:'Reactor Guardian'}[sub],m=modal(`Boss Mission: ${name}`,`<div class="ga-boss"><h3>⚔️ ${name}</h3><p>Score 8/10 or better in this ${sub} mission for a 40 KS2C boss bonus.</p><button id="bossGo" class="ga-btn">Start Boss Mission</button></div>`);m.querySelector('#bossGo').onclick=()=>{sessionStorage.setItem('ga-boss',sub);m.hidden=true;document.querySelector(`[data-subject="${sub}"]`)?.click()}}
function secret(){const all=[['waterfall','💎','Crystal Cave'],['library','🗝️','Hidden Library'],['garden','🌿','Knowledge Garden Vault'],['tower','🌟','Star Tower Roof']],n=all.find(x=>!e.secretFound.includes(x[0]));if(!n)return toast('All current secrets discovered!');e.secretFound.push(n[0]);save();award(15,'Secret found');modal('Secret Discovered!',`<div style="font-size:72px;text-align:center">${n[1]}</div><h2 style="text-align:center">${n[2]}</h2><p style="text-align:center">More secrets unlock as the academy grows.</p>`)}
function evolution(){const subs=['maths','english','science','computing','geography','history','french','art','design','music','pe','life'];modal('Your Evolving Academy',`<p>Mastery grows each subject area from a starter building into an academy landmark.</p>${subs.map(x=>`<div style="margin:11px 0"><strong>${x[0].toUpperCase()+x.slice(1)} — Stage ${stage(x)}/4</strong><div class="ga-progress"><i style="width:${mastery(x)}%"></i></div><small>${mastery(x)}% mastery</small></div>`).join('')}`)}
function friends(){modal('Safe Friends & Family',`<p>No unrestricted chat. Friend codes and preset reactions keep social play child-focused.</p><div class="ga-friend-code">${e.friendCode}</div><div class="ga-npc"><div class="ga-npc-face">🤝</div><div><strong>Family Challenge</strong><div>${e.familyProgress}/${e.familyGoal} correct answers this week</div><div class="ga-progress"><i style="width:${Math.min(100,e.familyProgress/e.familyGoal*100)}%"></i></div></div></div><p>Preset reactions: 🌟 Great job! · 🎉 Well done! · 💪 Keep going!</p>`)}
function arcade(){const games=[['maths','🏎️','Multiplication Race'],['english','🗺️','Spelling Treasure Hunt'],['computing','🤖','Robot Maze'],['french','🥐','French Café'],['geography','✈️','Geography Flight'],['science','🧪','Science Lab']],m=modal('Mini-game Arcade',`<p>Subject-themed challenges use the adaptive question engine, with dedicated interactive mechanics ready to expand independently.</p><div class="ga-mini-grid">${games.map(g=>`<button class="ga-mini" data-g="${g[0]}"><span>${g[1]}</span><strong>${g[2]}</strong><small>Play challenge</small></button>`).join('')}</div>`);m.querySelectorAll('[data-g]').forEach(b=>b.onclick=()=>{e.miniWins++;save();m.hidden=true;document.querySelector(`[data-subject="${b.dataset.g}"]`)?.click()})}
function share(){const a=app(),lvl=Math.max(1,Math.floor((a.xp||0)/180)+1),best=['maths','english','science','computing','geography','history','french','art','design','music','pe','life'].sort((x,y)=>mastery(y)-mastery(x))[0],text=`${a.childName||'Learner'} reached Level ${lvl} at Genius Academy and ${mastery(best)}% mastery in ${best}!`,m=modal('Share Achievement',`<div class="ga-share-card"><div class="trophy">🏆</div><h2>Genius Academy Achievement</h2><p>${text}</p><strong>Learning builds your world.</strong></div><button id="shareGo" class="ga-btn">Share achievement</button>`);m.querySelector('#shareGo').onclick=async()=>{if(navigator.share)await navigator.share({title:'Genius Academy Achievement',text});else{await navigator.clipboard?.writeText(text);toast('Achievement copied')}}}
function access(){const x=e.access,m=modal('Accessibility',`<div class="ga-access"><label>Large text <input type="checkbox" data-a="largeText" ${x.largeText?'checked':''}></label><label>Dyslexia-friendly spacing <input type="checkbox" data-a="dyslexia" ${x.dyslexia?'checked':''}></label><label>Reduced motion <input type="checkbox" data-a="reducedMotion" ${x.reducedMotion?'checked':''}></label><label>Higher contrast <input type="checkbox" data-a="highContrast" ${x.highContrast?'checked':''}></label><label>Read questions aloud <input type="checkbox" data-a="tts" ${x.tts?'checked':''}></label></div>`);m.querySelectorAll('[data-a]').forEach(i=>i.onchange=()=>{e.access[i.dataset.a]=i.checked;save()})}
function reward(){const m=modal('Parent-created Reward',`<p>Set a real-world reward controlled entirely by the parent.</p><input id="rw" class="ga-reward-input" value="${e.parentReward||''}" placeholder="Example: choose tonight’s film"><p>Unlock after <input id="rt" type="number" min="1" max="20" value="${e.parentRewardTarget||4}" style="width:70px"> daily missions.</p><button id="rs" class="ga-btn">Save</button>`);m.querySelector('#rs').onclick=()=>{e.parentReward=m.querySelector('#rw').value.trim();e.parentRewardTarget=Math.max(1,+m.querySelector('#rt').value||4);e.parentRewardClaimed=false;save();m.hidden=true;render();toast('Parent reward saved')}}
function story(){modal('The Genius Academy Story','<div class="ga-npc"><div class="ga-npc-face">🦉</div><div><strong>Professor Hoot</strong><p>The Academy’s Knowledge Crystals have dimmed. Every skill you master restores a building, opens a path and brings the world back to life. Restore all twelve subject districts to awaken the Grand Academy.</p></div></div>')}
function applyAccess(){const x=e.access||{};document.body.classList.toggle('ga-large-text',!!x.largeText);document.body.classList.toggle('ga-dyslexia',!!x.dyslexia);document.body.classList.toggle('ga-reduced-motion',!!x.reducedMotion);document.body.classList.toggle('ga-high-contrast',!!x.highContrast)}
function render(){sync();const home=document.querySelector('[data-view="home"]');if(!home)return;let h=document.getElementById('adventureHub');if(!h){h=document.createElement('section');h.id='adventureHub';h.className='adventure-hub';home.prepend(h)}const a=app(),d=a.daily?.done?.length||0,t=a.daily?.target||4,ready=d>=t&&e.lastChest!==today(),se=season();h.innerHTML=`<h2>🌟 Adventure Hub</h2><p>Your learning changes the world, unlocks companions and opens new adventures.</p><div class="ga-season"><strong>${se[0]} ${se[1]}</strong><small> — ${se[2]}</small></div><div class="adventure-grid"><div class="adventure-card"><strong>🎁 Daily Mystery Chest</strong><small>${ready?'Ready to open!':`${d}/${t} quests complete`}</small><button data-ga="chest">${ready?'Open chest':'Check chest'}</button></div><div class="adventure-card"><strong>${compIcon(e.companion)} ${compName(e.companion)}</strong><small>${e.unlockedCompanions.length} companions unlocked</small><button data-ga="companions">Companions</button></div><div class="adventure-card"><strong>${cosIcon(e.cosmetic)} Avatar Wardrobe</strong><small>${e.unlockedCosmetics.length} items unlocked</small><button data-ga="wardrobe">Customise</button></div><div class="adventure-card"><strong>⚔️ Boss Missions</strong><small>${e.bossWins} bosses defeated</small><button data-ga="boss">Face a boss</button></div><div class="adventure-card ga-secret"><strong>🗝️ Secret Areas</strong><small>${e.secretFound.length}/4 secrets found</small><button data-ga="secret">Explore</button></div><div class="adventure-card"><strong>🏰 Evolving Academy</strong><small>Buildings grow with mastery</small><button data-ga="evolution">View growth</button></div><div class="adventure-card"><strong>${e.league==='Diamond'?'💎':e.league==='Gold'?'🥇':e.league==='Silver'?'🥈':'🥉'} ${e.league} League</strong><small>${a.xp||0} XP</small><button data-ga="friends">Friends & family</button></div><div class="adventure-card"><strong>🎮 Mini-game Arcade</strong><small>Subject-themed challenges</small><button data-ga="arcade">Play</button></div><div class="adventure-card"><strong>🏆 Share Achievement</strong><small>Parent-shareable milestone</small><button data-ga="share">Create card</button></div><div class="adventure-card"><strong>♿ Accessibility</strong><small>Text, motion, contrast & speech</small><button data-ga="access">Settings</button></div><div class="adventure-card"><strong>👨‍👩‍👧 Parent Reward</strong><small>${e.parentReward||'Set a real-world reward'}</small><button data-ga="reward">Configure</button></div><div class="adventure-card"><strong>🦉 Professor Hoot</strong><small>Restore the Knowledge Crystals</small><button data-ga="story">Story</button></div></div>`;const f={chest,companions,wardrobe,boss,secret,evolution,friends,arcade,share,access,reward,story};h.querySelectorAll('[data-ga]').forEach(b=>b.onclick=()=>f[b.dataset.ga]())}
function checkBoss(){const sub=sessionStorage.getItem('ga-boss'),r=document.getElementById('reviewScore');if(!sub||!r)return;const m=r.textContent.match(/(\d+)\/10/);if(!m)return;sessionStorage.removeItem('ga-boss');if(+m[1]>=8){e.bossWins++;save();award(40,'Boss defeated');toast('⚔️ Boss defeated!')}}
function tts(){if(!e.access?.tts)return;const q=document.getElementById('question');if(q&&q.textContent&&q.dataset.spoken!==q.textContent){q.dataset.spoken=q.textContent;speechSynthesis?.cancel();speechSynthesis?.speak(new SpeechSynthesisUtterance(q.textContent))}}
window.GeniusEngagement={get:()=>e,stageFor:stage,averageSubject:mastery,compIcon,labelCompanion:compName};
addEventListener('DOMContentLoaded',()=>{applyAccess();sync();render();setInterval(()=>{checkBoss();tts()},700);setInterval(render,5000)});
})();
