(()=>{
const E='ks2-engagement-v1',A='ks2genius-v1';
const get=(k,f={})=>{try{return {...f,...JSON.parse(localStorage.getItem(k)||'{}')}}catch{return f}};
const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function s(){return get(E,{friends:[],access:{}})}function a(){return get(A,{daily:{done:[]},xp:0,childName:'Learner'})}
function companionIcon(id){return ({owl:'🦉',fox:'🦊',robot:'🤖',dragon:'🐉',unicorn:'🦄'})[id]||'🦉'}
function ensureWorldCompanion(){const world=document.querySelector('.world-shell');if(!world)return;let c=document.getElementById('gaWorldCompanion');if(!c){c=document.createElement('button');c.id='gaWorldCompanion';c.setAttribute('aria-label','Open companions');c.style.cssText='position:absolute;z-index:14;left:14px;bottom:18px;width:54px;height:54px;border-radius:50%;border:2px solid #ffe58c;background:rgba(18,46,100,.92);font-size:30px;box-shadow:0 8px 22px #0004;display:grid;place-items:center';world.append(c);c.onclick=()=>document.querySelector('[data-nav="home"]')?.click()}const st=s();c.textContent=companionIcon(st.companion);c.title='Your companion is exploring with you';}
function enhanceParentReward(){const st=s(),app=a(),done=(app.daily?.done||[]).length;if(!st.parentReward)return;let box=document.getElementById('gaParentRewardStatus');const parent=document.querySelector('[data-view="parent"]');if(!parent)return;if(!box){box=document.createElement('section');box.id='gaParentRewardStatus';box.className='section panel';parent.insertBefore(box,parent.children[1]||null)}const ready=done>=(st.parentRewardTarget||4)&&!st.parentRewardClaimed;box.innerHTML=`<div class="section-title"><h2>🎁 Parent Reward</h2><small>${done}/${st.parentRewardTarget||4} missions</small></div><p><strong>${st.parentReward}</strong></p>${ready?'<button class="primary" id="gaClaimParentReward">Parent confirms reward given ✓</button>':st.parentRewardClaimed?'<p>✅ Reward confirmed as given.</p>':'<p>Complete more missions to unlock this reward.</p>'}`;box.querySelector('#gaClaimParentReward')?.addEventListener('click',()=>{const n=s();n.parentRewardClaimed=true;set(E,n);enhanceParentReward()})}
function friendPanel(){const parent=document.querySelector('[data-view="parent"]');if(!parent)return;let box=document.getElementById('gaSafeFriends');if(!box){box=document.createElement('section');box.id='gaSafeFriends';box.className='section panel';parent.append(box)}const st=s();box.innerHTML=`<div class="section-title"><h2>🤝 Safe Friends</h2><small>No open chat</small></div><p>Saved friend codes: <strong>${(st.friends||[]).length}</strong></p><div style="display:flex;gap:8px;flex-wrap:wrap"><input id="gaFriendInput" class="ga-reward-input" style="flex:1;min-width:180px" placeholder="Enter a Genius Academy friend code"><button id="gaAddFriend" class="primary">Add</button></div>${(st.friends||[]).map(x=>`<p>🌟 ${x} — preset reactions: 🎉 💪 ⭐</p>`).join('')}`;box.querySelector('#gaAddFriend')?.addEventListener('click',()=>{const input=box.querySelector('#gaFriendInput'),code=input.value.trim().toUpperCase();if(!/^GA[A-Z0-9]{6}$/.test(code))return;const n=s();n.friends=[...new Set([...(n.friends||[]),code])].slice(0,20);set(E,n);friendPanel()})}
function adaptiveBanner(){const home=document.querySelector('[data-view="home"]');if(!home)return;let el=document.getElementById('gaAdaptiveUnlock');if(!el){el=document.createElement('div');el.id='gaAdaptiveUnlock';el.className='ga-npc';const hub=document.getElementById('adventureHub');(hub||home).append(el)}const app=a(),xp=app.xp||0,next=xp<250?'Pixel Fox at 250 XP':xp<600?'Byte Bot at 600 XP':xp<1200?'Fraction Dragon at 1,200 XP':xp<2200?'Nova Unicorn at 2,200 XP':'Diamond Academy Crown';el.innerHTML=`<div class="ga-npc-face">🦉</div><div><strong>Professor Hoot’s next unlock</strong><div>${next}</div><small>Your academy changes as your mastery rises.</small></div>`}
function tick(){ensureWorldCompanion();enhanceParentReward();friendPanel();adaptiveBanner()}
window.addEventListener('DOMContentLoaded',()=>{tick();setInterval(tick,3500)});window.addEventListener('ga-companion',ensureWorldCompanion);
})();
