(()=>{
const W='ks2-world-v1',E='ks2-engagement-v1';
const read=(k,f={})=>{try{return {...f,...JSON.parse(localStorage.getItem(k)||'{}')}}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const shuffle=a=>[...a].sort(()=>Math.random()-.5),pick=a=>a[Math.floor(Math.random()*a.length)];
const DATA={
 maths:{pairs:[['6 × 7','42'],['8 × 4','32'],['9 × 3','27'],['7 × 8','56'],['1/2','2/4'],['3/4','6/8'],['£2.50 + £1.25','£3.75'],['100 ÷ 4','25']],sort:[['24','Even'],['17','Odd'],['36','Even'],['51','Odd'],['1/2','Fraction'],['3/5','Fraction']],bins:['Even','Odd','Fraction'],runner:[['7 × 6',['40','42','48'],'42'],['9 × 4',['36','32','45'],'36'],['56 ÷ 7',['7','8','9'],'8']],build:[['5 × 8',['35','40','45'],'40'],['72 ÷ 8',['8','9','10'],'9'],['3/4 of 20',['12','15','18'],'15']]},
 english:{pairs:[['Happiness','Abstract noun'],['London','Proper noun'],['teacher','Common noun'],['rapid','fast'],['enormous','huge'],['ran','verb'],['beautiful','adjective'],['quietly','adverb']],sort:[['London','Proper'],['school','Common'],['bravery','Abstract'],['Martin','Proper'],['chair','Common'],['joy','Abstract']],bins:['Proper','Common','Abstract'],runner:[['Which is a verb?',['blue','jump','happy'],'jump'],['Which is an adjective?',['soft','quickly','sing'],'soft'],['Which is abstract?',['desk','hope','Paris'],'hope']]},
 science:{pairs:[['Evaporation','Liquid → gas'],['Freezing','Liquid → solid'],['Mercury','Planet'],['Heart','Circulates blood'],['Roots','Absorb water'],['Producer','Plant']],sort:[['ice','Solid'],['water','Liquid'],['steam','Gas'],['oxygen','Gas'],['juice','Liquid'],['rock','Solid']],bins:['Solid','Liquid','Gas'],runner:[['Which is a conductor?',['wood','metal','plastic'],'metal'],['Which organ pumps blood?',['heart','lungs','stomach'],'heart']]},
 geography:{pairs:[['France','Paris'],['Italy','Rome'],['Japan','Tokyo'],['Egypt','Cairo'],['Brazil','Brasília'],['Australia','Canberra']],sort:[['France','Europe'],['Kenya','Africa'],['Japan','Asia'],['Brazil','South America'],['Canada','North America'],['India','Asia']],bins:['Europe','Asia','Americas']},
 history:{pairs:[['Romans','Ancient'],['Victorians','1800s'],['WWII','1939–1945'],['Norman Conquest','1066'],['Great Fire of London','1666'],['Moon landing','1969']],timeline:[['Norman Conquest',1066],['Great Fire of London',1666],['Victorian era',1837],['WWII begins',1939],['Moon landing',1969]]},
 french:{pairs:[['bonjour','hello'],['merci','thank you'],['chat','cat'],['chien','dog'],['rouge','red'],['bleu','blue'],['pomme','apple'],['eau','water']],shop:[['Je voudrais une pomme','🍎 apple'],['Je voudrais de l’eau','💧 water'],['Je voudrais du pain','🥖 bread']]},
 computing:{pairs:[['Algorithm','A sequence of steps'],['Bug','A mistake in code'],['Loop','Repeat instructions'],['Variable','Stores a value'],['Password','Secret access phrase']],sort:[['Repeat 4 times','Loop'],['Move forward','Command'],['If wall then turn','Condition'],['Turn left','Command']],bins:['Command','Loop','Condition']},
 life:{pairs:[['Red traffic light','Stop'],['Smoke alarm','Leave and tell an adult'],['Dirty plate','Wash it'],['Wet floor','Walk carefully'],['£5 budget','Spend £5 or less']],sort:[['T-shirt','Laundry'],['Plate','Dishwasher'],['Book','Shelf'],['Sock','Laundry'],['Cup','Dishwasher'],['Toy','Shelf']],bins:['Laundry','Dishwasher','Shelf']}
};
const GAMES=[
['association','🃏','Association Solitaire','Match linked knowledge cards','English'],['bubbles','🫧','Bubble Match','Pop the correct answer before it floats away','Maths'],['sort','📦','Sorting Conveyor','Flick ideas into the right category','Science'],['memory','🧠','Memory Match','Find all the hidden learning pairs','French'],['runner','🏃','Number Dash','Run through the correct answer gate','Maths'],['robot','🤖','Robot Maze','Program a robot to reach the goal','Computing'],['tower','🏗️','Tower Builder','Earn and place blocks by solving challenges','Maths'],['sentence','🧩','Sentence Jigsaw','Rebuild scrambled sentences','English'],['timeline','⏳','Timeline Race','Put historical events in order','History'],['cafe','🥐','French Café','Serve customers from French orders','French'],['treasure','💎','Treasure Connect','Chain related concepts to unlock treasure','Geography'],['boss','🐉','Boss Battle','Use knowledge attacks to defeat the boss','Mixed']
];
const CATALOG=[
...GAMES,
['bubbles','🥷','Noun Ninja','Pop only the requested noun type','English'],['runner','🔤','Spelling Runner','Choose the correct spelling gate','English'],['sentence','✍️','Punctuation Rescue','Rebuild and repair sentences','English'],['treasure','🔗','Synonym Chain','Connect words with similar meanings','English'],
['tower','🌉','Bridge Builder','Build a bridge with maths rewards','Maths'],['runner','☄️','Times Table Blaster','Fast multiplication challenge','Maths'],['sort','💷','Money Shop Sort','Sort prices and change correctly','Maths'],['treasure','🍕','Fraction Connect','Match equivalent fractions visually','Maths'],
['sort','🧪','States of Matter Lab','Sort solids, liquids and gases','Science'],['treasure','🌱','Food Chain Links','Connect producers and consumers','Science'],['tower','🔌','Circuit Builder','Earn circuit pieces with science skills','Science'],
['treasure','🗺️','Capital Quest','Connect countries and capitals','Geography'],['memory','🚩','Flag Memory','Match places and world facts','Geography'],['sort','🌦️','Weather Studio','Sort weather and climate clues','Geography'],
['timeline','🏺','Time Portal','Restore events in chronological order','History'],['memory','⛏️','Archaeology Dig','Reveal and pair historical clues','History'],
['cafe','🧳','French Suitcase','Choose the right French vocabulary','French'],['memory','🇫🇷','French Snap Memory','Rapid French-English matching','French'],
['robot','🐞','Debug the Robot','Repair a broken command sequence','Computing'],['sort','🛡️','Cyber Safety Detective','Sort safe and unsafe choices','Computing'],
['sort','🧺','Laundry Sort','Complete real household jobs','Life Skills'],['cafe','🛒','Supermarket Challenge','Choose useful items and stay on budget','Life Skills'],['sentence','⏰','Morning Routine Race','Put daily steps in a sensible order','Life Skills'],
['boss','🏰','Castle Raid','Beat a mixed-subject challenge boss','Mixed'],['boss','🔐','Escape Room','Solve a chain of curriculum puzzles','Mixed']
];
let modal,stage,titleEl,scoreEl,game={score:0,round:0,lives:3,subject:'maths',type:'association'};
function coins(n){const w=read(W,{coins:0,earned:0});w.coins=(w.coins||0)+n;w.earned=(w.earned||0)+n;write(W,w);dispatchEvent(new Event('ks2coins'))}
function ensureModal(){if(modal)return;modal=document.createElement('div');modal.className='ga-game-modal';modal.hidden=true;modal.innerHTML='<section class="ga-game-shell"><header class="ga-game-top"><button class="back">←</button><div class="ga-game-title"><strong id="mgTitle">Mini-game</strong><small id="mgSub">Genius Academy Arcade</small></div><div class="ga-game-score"><span>⭐ <b id="mgScore">0</b></span><span>❤️ <b id="mgLives">3</b></span></div></header><div class="ga-game-stage" id="mgStage"></div></section>';document.body.append(modal);stage=modal.querySelector('#mgStage');titleEl=modal.querySelector('#mgTitle');scoreEl=modal.querySelector('#mgScore');modal.querySelector('.back').onclick=close;}
function update(){scoreEl.textContent=game.score;modal.querySelector('#mgLives').textContent=game.lives}
function feedback(text,good=true){const f=document.createElement('div');f.className='ga-feedback '+(good?'good':'bad');f.textContent=text;stage.append(f);setTimeout(()=>f.remove(),1000)}
function winRound(points=10){game.score+=points;game.round++;coins(2);update();feedback('✨ Nice! +2 KS2C');if(game.round>=5)return setTimeout(finish,700);setTimeout(()=>renderType(),650)}
function miss(msg='Try again!'){game.lives--;update();feedback(msg,false);if(game.lives<=0)setTimeout(finish,700)}
function finish(){stage.innerHTML=`<div style="text-align:center;padding:40px 12px"><div style="font-size:76px">🏆</div><h2>Game complete!</h2><p>You scored <strong>${game.score}</strong> points.</p><button class="ga-btn" id="again">Play again</button> <button class="ga-btn" id="arc">Choose another game</button></div>`;stage.querySelector('#again').onclick=()=>start(game.type,game.subject,game.name);stage.querySelector('#arc').onclick=()=>{close();document.getElementById('gaArcade')?.scrollIntoView({behavior:'smooth'})}}
function close(){modal.hidden=true;document.body.style.overflow=''}
function start(type,subject='maths',name){ensureModal();game={type,subject,score:0,round:0,lives:3,name:name||type};titleEl.textContent=name||type;modal.querySelector('#mgSub').textContent=(subject==='mixed'?'Mixed subjects':subject[0].toUpperCase()+subject.slice(1));modal.hidden=false;document.body.style.overflow='hidden';update();renderType()}
function pairsFor(){const d=DATA[game.subject]||DATA.maths;return d.pairs||DATA.maths.pairs}
function renderType(){if(game.lives<=0)return finish();({association,bubbles,sort,memory,runner,robot,tower,sentence,timeline,cafe,treasure,boss}[game.type]||association)()}
function association(){const ps=shuffle(pairsFor()).slice(0,5),left=shuffle(ps.map(x=>x[0])),right=shuffle(ps.map(x=>x[1]));let chosen=null;stage.innerHTML='<p class="ga-game-instruction">Match each card with its partner.</p><div class="ga-card-columns"><div id="aL"></div><div id="aR"></div></div>';const make=(txt,side)=>{const b=document.createElement('button');b.className='ga-match-card';b.textContent=txt;b.onclick=()=>{if(!chosen){chosen={txt,side,b};b.classList.add('selected');return}if(chosen.side===side){chosen.b.classList.remove('selected');chosen={txt,side,b};b.classList.add('selected');return}const a=side==='L'?[txt,chosen.txt]:[chosen.txt,txt],ok=ps.some(p=>p[0]===a[0]&&p[1]===a[1]);if(ok){b.classList.add('done');chosen.b.classList.add('done');game.score+=5;update();feedback('Match!');if(stage.querySelectorAll('.done').length===10)setTimeout(()=>winRound(10),500)}else miss('Those do not match');chosen.b.classList.remove('selected');chosen=null};return b};left.forEach(x=>stage.querySelector('#aL').append(make(x,'L')));right.forEach(x=>stage.querySelector('#aR').append(make(x,'R')))}
function bubbles(){const d=DATA[game.subject]||DATA.maths,source=d.runner||DATA.maths.runner,q=pick(source);stage.innerHTML=`<div class="ga-prompt">${q[0]}</div><div class="ga-bubble-field" id="bf"></div>`;const opts=shuffle(q[1]);opts.concat(opts.slice(0,2)).forEach((x,i)=>{const b=document.createElement('button');b.className='ga-bubble';b.textContent=x;b.style.left=(6+(i%4)*23)+'%';b.style.top=(62+Math.floor(i/4)*22)+'%';b.style.animationDelay=(-i*.65)+'s';b.onclick=()=>x===q[2]?winRound(12):(b.remove(),miss('Wrong bubble'));stage.querySelector('#bf').append(b)})}
function sort(){const d=DATA[game.subject]||DATA.english,items=shuffle(d.sort||DATA.english.sort).slice(0,6),bins=d.bins||DATA.english.bins;let selected=null,done=0;stage.innerHTML='<p class="ga-game-instruction">Tap an item, then tap the correct bin.</p><div class="ga-sort-source" id="ss"></div><div class="ga-sort-bins" id="sb"></div>';items.forEach(([v,c],i)=>{const b=document.createElement('button');b.className='ga-sort-item';b.textContent=v;b.dataset.c=c;b.onclick=()=>{stage.querySelectorAll('.ga-sort-item').forEach(x=>x.classList.remove('selected'));selected=b;b.classList.add('selected')};stage.querySelector('#ss').append(b)});bins.forEach(c=>{const b=document.createElement('button');b.className='ga-bin';b.innerHTML=`<strong>${c}</strong>`;b.onclick=()=>{if(!selected)return;if(selected.dataset.c===c){selected.remove();done++;feedback('Sorted!');selected=null;if(done===items.length)winRound(12)}else miss('Wrong bin')};stage.querySelector('#sb').append(b)})}
function memory(){const ps=shuffle(pairsFor()).slice(0,4),cards=shuffle(ps.flatMap((p,i)=>[{t:p[0],id:i},{t:p[1],id:i}]));let open=[];stage.innerHTML='<p class="ga-game-instruction">Find all four matching pairs.</p><div class="ga-memory-grid" id="mem"></div>';cards.forEach(c=>{const b=document.createElement('button');b.className='ga-memory';b.textContent='?';b.onclick=()=>{if(b.classList.contains('done')||open.includes(b)||open.length===2)return;b.classList.add('open');b.textContent=c.t;b.dataset.id=c.id;open.push(b);if(open.length===2)setTimeout(()=>{if(open[0].dataset.id===open[1].dataset.id){open.forEach(x=>x.classList.add('done'));feedback('Pair found!');if(stage.querySelectorAll('.done').length===8)winRound(15)}else{open.forEach(x=>{x.classList.remove('open');x.textContent='?'});miss('Not a pair')}open=[]},500)};stage.querySelector('#mem').append(b)})}
function runner(){const d=DATA[game.subject]||DATA.maths,q=pick(d.runner||DATA.maths.runner),opts=q[1];stage.innerHTML=`<div class="ga-prompt">${q[0]}</div><div class="ga-runner"><div class="ga-road"></div><div class="ga-gates" id="gates"></div><div class="ga-runner-player">🏃</div></div><div class="ga-runner-controls"><button>⬅ Left</button><button>⬆ Centre</button><button>Right ➡</button></div>`;opts.forEach((x,i)=>{const b=document.createElement('button');b.className='ga-gate';b.textContent=x;b.onclick=()=>{stage.querySelector('.ga-runner-player').style.left=[20,50,80][i]+'%';setTimeout(()=>x===q[2]?winRound(14):miss('Wrong gate'),250)};stage.querySelector('#gates').append(b)});stage.querySelectorAll('.ga-runner-controls button').forEach((b,i)=>b.onclick=()=>stage.querySelectorAll('.ga-gate')[i].click())}
function robot(){const maze=[[0,0,1,0,0,0],[1,0,1,0,1,0],[0,0,0,0,1,0],[0,1,1,0,0,0],[0,0,0,0,1,1],[0,1,0,0,0,2]];let x=0,y=0,dir=1,program=[];stage.innerHTML='<p class="ga-game-instruction">Program Byte Bot to reach ⭐. Avoid walls.</p><div class="ga-maze" id="maze"></div><div class="ga-program" id="prog">Your program…</div><div class="ga-codebar"><button data-c="F">⬆ Forward</button><button data-c="L">↶ Left</button><button data-c="R">↷ Right</button><button data-c="RUN">▶ Run</button><button data-c="CLR">Clear</button></div>';const draw=()=>{const m=stage.querySelector('#maze');m.innerHTML='';maze.forEach((row,yy)=>row.forEach((v,xx)=>{const c=document.createElement('div');c.className='ga-cell '+(v===1?'wall':v===2?'goal':'')+(xx===x&&yy===y?' robot':'');c.textContent=xx===x&&yy===y?'🤖':v===2?'⭐':'';m.append(c)}))};draw();stage.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{const c=b.dataset.c;if(c==='CLR'){program=[];stage.querySelector('#prog').textContent='Your program…';return}if(c!=='RUN'){program.push(c);stage.querySelector('#prog').innerHTML=program.map(z=>`<span>${z==='F'?'⬆':z==='L'?'↶':'↷'}</span>`).join('');return}for(const z of program){if(z==='L')dir=(dir+3)%4;else if(z==='R')dir=(dir+1)%4;else{const ds=[[0,-1],[1,0],[0,1],[-1,0]],nx=x+ds[dir][0],ny=y+ds[dir][1];if(ny<0||ny>=6||nx<0||nx>=6||maze[ny][nx]===1){miss('Byte Bot hit a wall');break}x=nx;y=ny}}draw();if(maze[y][x]===2)winRound(20);program=[]})}
function tower(){const q=pick((DATA[game.subject]||DATA.maths).build||DATA.maths.build);stage.innerHTML=`<div class="ga-prompt">${q[0]}</div><div class="ga-build-zone"><div class="ga-foundation"></div><div id="blocks"></div></div><div class="ga-build-answer" id="ba"></div>`;q[1].forEach(x=>{const b=document.createElement('button');b.textContent=x;b.onclick=()=>{if(x!==q[2])return miss('That block will not fit');const z=stage.querySelector('#blocks'),bl=document.createElement('div');bl.className='ga-block';const n=z.children.length;bl.style.left=(22+(n%6)*10)+'%';bl.style.bottom=(48+Math.floor(n/6)*38)+'px';z.append(bl);winRound(15)};stage.querySelector('#ba').append(b)})}
const SENTENCES=[['The quick fox jumps over the log.',['The','quick','fox','jumps','over','the','log.']],['London is the capital of England.',['London','is','the','capital','of','England.']],['Plants need light and water to grow.',['Plants','need','light','and','water','to','grow.']]];
function sentence(){const s=pick(SENTENCES),chosen=[];stage.innerHTML=`<p class="ga-game-instruction">Build the sentence in the correct order.</p><div class="ga-sequence-target" id="target"></div><div class="ga-chip-bank" id="bank"></div><button class="ga-btn" id="check">Check sentence</button>`;shuffle(s[1]).forEach(w=>{const b=document.createElement('button');b.className='ga-chip';b.textContent=w;b.onclick=()=>{if(b.classList.contains('used'))return;b.classList.add('used');chosen.push(w);const c=document.createElement('span');c.className='ga-chip';c.textContent=w;stage.querySelector('#target').append(c)};stage.querySelector('#bank').append(b)});stage.querySelector('#check').onclick=()=>chosen.join(' ')===s[1].join(' ')?winRound(18):(chosen.length=0,stage.querySelector('#target').innerHTML='',stage.querySelectorAll('#bank .ga-chip').forEach(x=>x.classList.remove('used')),miss('Rebuild the sentence'))}
function timeline(){const arr=shuffle((DATA.history.timeline||[]).slice()),chosen=[];stage.innerHTML='<p class="ga-game-instruction">Tap the events from earliest to latest.</p><div class="ga-sequence-target" id="target"></div><div class="ga-chip-bank" id="bank"></div><button class="ga-btn" id="check">Check timeline</button>';arr.forEach(([n,y])=>{const b=document.createElement('button');b.className='ga-chip';b.textContent=n;b.onclick=()=>{if(b.classList.contains('used'))return;b.classList.add('used');chosen.push([n,y]);const c=document.createElement('span');c.className='ga-chip';c.textContent=n;stage.querySelector('#target').append(c)};stage.querySelector('#bank').append(b)});stage.querySelector('#check').onclick=()=>chosen.length===arr.length&&chosen.every((x,i,a)=>i===0||a[i-1][1]<x[1])?winRound(20):miss('Check the order')}
function cafe(){const orders=(DATA[game.subject]||DATA.french).shop||DATA.french.shop,q=pick(orders),items=shuffle(['🍎 apple','💧 water','🥖 bread','🧀 cheese']);let sel='';stage.innerHTML=`<div class="ga-shop"><div class="ga-customer"><div class="face">🧑‍🍳</div><h3>Customer says:</h3><p>${q[0]}</p></div><div class="ga-tray"><strong>Choose the item</strong><div class="ga-shop-items" id="items"></div><button class="ga-btn" id="serve">Serve</button></div></div>`;items.forEach(x=>{const b=document.createElement('button');b.className='ga-shop-item';b.textContent=x;b.onclick=()=>{stage.querySelectorAll('.ga-shop-item').forEach(z=>z.classList.remove('selected'));b.classList.add('selected');sel=x};stage.querySelector('#items').append(b)});stage.querySelector('#serve').onclick=()=>sel===q[1]?winRound(16):miss('That is not the order')}
function treasure(){const ps=shuffle(pairsFor()).slice(0,6),tiles=shuffle(ps.flatMap((p,i)=>[{t:p[0],id:i},{t:p[1],id:i}]));let first=null,done=0;stage.innerHTML='<p class="ga-game-instruction">Connect matching concepts to collect treasure.</p><div class="ga-treasure-grid" id="tg"></div>';tiles.forEach(c=>{const b=document.createElement('button');b.className='ga-treasure-tile';b.textContent=c.t;b.dataset.id=c.id;b.onclick=()=>{if(b.classList.contains('done'))return;if(!first){first=b;b.classList.add('selected');return}if(first===b)return;if(first.dataset.id===b.dataset.id){first.classList.add('done');b.classList.add('done');first.classList.remove('selected');first=null;done++;feedback('💎 Treasure!');if(done===ps.length)winRound(20)}else{first.classList.remove('selected');first=null;miss('Chain broken')}};stage.querySelector('#tg').append(b)})}
function boss(){const d=DATA.maths.runner,q=pick(d),boss=pick(['🐉','🧙','🤖','👾']);game.bossHP=game.bossHP??100;stage.innerHTML=`<div class="ga-boss-arena"><div class="ga-boss-sprite">${boss}</div><strong>Boss health</strong><div class="ga-health"><i style="width:${game.bossHP}%"></i></div><div class="ga-prompt">${q[0]}</div><div class="ga-boss-actions" id="acts"></div></div>`;q[1].forEach(x=>{const b=document.createElement('button');b.textContent=x;b.onclick=()=>{if(x===q[2]){game.bossHP-=25;game.score+=20;coins(3);update();feedback('⚡ Critical hit!');if(game.bossHP<=0){game.bossHP=null;setTimeout(()=>winRound(30),500)}else setTimeout(boss,500)}else miss('The boss blocked it!')};stage.querySelector('#acts').append(b)})}
function renderArcade(){const home=document.querySelector('[data-view="home"]');if(!home||document.getElementById('gaArcade'))return;const s=document.createElement('section');s.id='gaArcade';s.className='ga-arcade';s.innerHTML=`<div class="ga-arcade-head"><div><h2>🎮 Genius Arcade</h2><p>Real games where the learning is the mechanic — not just four answer buttons.</p></div><span class="ga-arcade-badge">${CATALOG.length} games</span></div><div class="ga-game-grid"></div>`;const grid=s.querySelector('.ga-game-grid');CATALOG.forEach(([type,ico,name,desc,sub])=>{const b=document.createElement('button');b.className='ga-game-card';b.innerHTML=`<span class="ico">${ico}</span><strong>${name}</strong><small>${desc}</small><span class="tag">${sub}</span>`;b.onclick=()=>start(type,sub==='Mixed'?'maths':sub.toLowerCase().replace(' skills',''),name);grid.append(b)});home.insertBefore(s,home.querySelector('.section.daily-card'))}
function hookEngagement(){document.addEventListener('click',e=>{const b=e.target.closest('[data-ga="arcade"]');if(!b)return;setTimeout(()=>{const m=document.getElementById('gaModal');if(m)m.hidden=true;document.querySelector('[data-nav="home"]')?.click();setTimeout(()=>document.getElementById('gaArcade')?.scrollIntoView({behavior:'smooth'}),80)},0)},true)}
window.GeniusMiniGames={start,openArcade:()=>{document.querySelector('[data-nav="home"]')?.click();document.getElementById('gaArcade')?.scrollIntoView({behavior:'smooth'})},catalog:CATALOG};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{renderArcade();hookEngagement()});else{renderArcade();hookEngagement()}
})();
