(()=>{
const WORLD_KEY='ks2-world-v1',ACADEMY_KEY='ks2genius-v1';
const read=(k,f={})=>{try{return {...f,...JSON.parse(localStorage.getItem(k)||'{}')}}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const defaultWorld=()=>({coins:0,earned:0,spent:0,owned:[],player2d:{x:50,y:78}});
let world=read(WORLD_KEY,defaultWorld());
const BUILD_ITEMS=[
{id:'desk',name:'Genius Desk',icon:'📚',cost:40,desc:'A study desk for your academy base.'},{id:'garden',name:'Knowledge Garden',icon:'🌳',cost:70,desc:'A colourful knowledge garden.'},{id:'robot',name:'Helper Robot',icon:'🤖',cost:110,desc:'A friendly learning companion.'},{id:'lab',name:'Mini Science Lab',icon:'🔬',cost:150,desc:'A glowing experiment wing.'},{id:'tower',name:'Trophy Tower',icon:'🏆',cost:220,desc:'Display your mastery trophies.'},{id:'portal',name:'Challenge Portal',icon:'🌀',cost:300,desc:'Unlock an expert challenge portal.'}
];
const SUBJECTS={
 maths:{name:'Math Manor',icon:'➗',x:24,y:28,kind:'castle'},english:{name:'Story Keep',icon:'📚',x:50,y:20,kind:'keep'},science:{name:'Science Lab',icon:'🔬',x:20,y:52,kind:'lab'},computing:{name:'Code Core',icon:'💻',x:63,y:72,kind:'tower'},geography:{name:'Explorer Lodge',icon:'🌍',x:41,y:68,kind:'lodge'},history:{name:'Time Temple',icon:'🏺',x:82,y:58,kind:'temple'},french:{name:'French Café',icon:'🇫🇷',x:13,y:72,kind:'cafe'},art:{name:'Creator Studio',icon:'🎨',x:82,y:29,kind:'studio'},design:{name:'Maker Works',icon:'🛠️',x:10,y:34,kind:'works'},music:{name:'Sound Stage',icon:'🎵',x:70,y:38,kind:'stage'},pe:{name:'Power Arena',icon:'🏃',x:84,y:76,kind:'arena'},life:{name:'Think Tower',icon:'💡',x:66,y:54,kind:'think'}
};
const canvas=document.getElementById('worldCanvas'),ctx=canvas?.getContext('2d');if(!canvas||!ctx)return;
const nearbyCard=document.getElementById('worldNearby'),nearbyName=document.getElementById('nearbyName'),nearbyIcon=document.getElementById('nearbyIcon'),nearbyAction=document.getElementById('nearbyAction'),action=document.getElementById('worldAction'),gestureHint=document.getElementById('gestureHint'),basePanel=document.getElementById('basePanel'),shop=document.getElementById('buildShop');
let player=world.player2d||{x:50,y:78},target=null,nearby=null,zoom=1,drag=null,pinch=null,gestureDismissed=false,last=performance.now();
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(r.width*d));canvas.height=Math.max(1,Math.round(r.height*d));ctx.setTransform(d,0,0,d,0,0);}addEventListener('resize',resize);resize();
function dismissHint(){if(gestureDismissed)return;gestureDismissed=true;gestureHint?.classList.add('hide');setTimeout(()=>{if(gestureHint)gestureHint.hidden=true},500)}
function startSubject(id){document.querySelector(`[data-subject="${id}"]`)?.click();}
function mapRect(){const r=canvas.getBoundingClientRect(),pad=22;return{x:pad,y:pad,w:r.width-pad*2,h:r.height-pad*2};}
function screen(p){const m=mapRect(),cx=m.x+m.w/2,cy=m.y+m.h/2;return{x:cx+(p.x-50)*m.w/100*zoom,y:cy+(p.y-50)*m.h/100*zoom};}
function worldPoint(x,y){const m=mapRect(),cx=m.x+m.w/2,cy=m.y+m.h/2;return{x:50+(x-cx)/(m.w*zoom)*100,y:50+(y-cy)/(m.h*zoom)*100};}
function rounded(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);}
function road(a,b){const A=screen(a),B=screen(b);ctx.strokeStyle='rgba(232,197,132,.95)';ctx.lineWidth=16*zoom;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(A.x,A.y);ctx.lineTo(B.x,B.y);ctx.stroke();ctx.strokeStyle='rgba(255,245,210,.62)';ctx.lineWidth=3*zoom;ctx.setLineDash([10*zoom,12*zoom]);ctx.beginPath();ctx.moveTo(A.x,A.y);ctx.lineTo(B.x,B.y);ctx.stroke();ctx.setLineDash([])}
function drawBuilding(id,s){const p=screen(s),scale=clamp(zoom,.72,1.18),w=72*scale,h=58*scale,x=p.x-w/2,y=p.y-h/2;ctx.save();ctx.shadowColor='rgba(22,48,72,.18)';ctx.shadowBlur=14;ctx.shadowOffsetY=7;rounded(x,y,w,h,16);ctx.fillStyle=id==='science'?'#dff5ff':id==='computing'?'#e9e4ff':id==='art'?'#ffe8f2':id==='pe'?'#e2f7e7':'#fff4d5';ctx.fill();ctx.shadowColor='transparent';ctx.fillStyle=id==='science'?'#4094c8':id==='computing'?'#6659c9':id==='art'?'#d85f91':id==='pe'?'#46a864':'#c7863e';ctx.beginPath();ctx.moveTo(x-4,y+8);ctx.lineTo(x+w/2,y-20*scale);ctx.lineTo(x+w+4,y+8);ctx.closePath();ctx.fill();ctx.font=`${28*scale}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(s.icon,p.x,p.y+3*scale);ctx.font=`600 ${11*scale}px system-ui`;ctx.fillStyle='#16364a';ctx.fillText(s.name,p.x,p.y+h/2+17*scale);ctx.restore()}
function tree(x,y,r=7){const p=screen({x,y});ctx.fillStyle='#4b9c55';ctx.beginPath();ctx.arc(p.x,p.y,r*zoom,0,Math.PI*2);ctx.fill();ctx.fillStyle='#34783d';ctx.beginPath();ctx.arc(p.x-r*.4*zoom,p.y-r*.3*zoom,r*.55*zoom,0,Math.PI*2);ctx.fill()}
function draw(){const r=canvas.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);const g=ctx.createLinearGradient(0,0,0,r.height);g.addColorStop(0,'#9fe3ff');g.addColorStop(.22,'#bdeeff');g.addColorStop(.221,'#79c96b');g.addColorStop(1,'#5fb657');ctx.fillStyle=g;ctx.fillRect(0,0,r.width,r.height);const m=mapRect();ctx.save();rounded(m.x,m.y,m.w,m.h,28);ctx.clip();ctx.fillStyle='rgba(118,206,98,.76)';ctx.fillRect(m.x,m.y,m.w,m.h);const pond=screen({x:48,y:45});ctx.fillStyle='rgba(83,184,226,.88)';ctx.beginPath();ctx.ellipse(pond.x,pond.y,92*zoom,52*zoom,-.18,0,Math.PI*2);ctx.fill();road({x:50,y:88},{x:50,y:20});road({x:14,y:72},{x:84,y:76});road({x:10,y:34},{x:82,y:29});road({x:20,y:52},{x:82,y:58});for(let i=0;i<34;i++)tree(5+(i*17)%91,8+(i*29)%84,4+(i%3));Object.entries(SUBJECTS).forEach(([id,s])=>drawBuilding(id,s));const pp=screen(player);ctx.save();ctx.shadowColor='rgba(0,0,0,.25)';ctx.shadowBlur=8;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(pp.x,pp.y,18,0,Math.PI*2);ctx.fill();ctx.shadowColor='transparent';ctx.font='25px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('🧑‍🚀',pp.x,pp.y);ctx.restore();ctx.restore();}
function updateNearby(){let best=null,bd=999;for(const [id,s] of Object.entries(SUBJECTS)){const d=dist(player,s);if(d<bd){bd=d;best={id,...s,d}}}nearby=bd<9?best:null;if(nearby){nearbyCard.hidden=false;nearbyName.textContent=nearby.name;nearbyIcon.textContent=nearby.icon;nearbyAction.textContent=nearby.d<5?'Ready to enter':'Walk closer';action.hidden=nearby.d>=5;action.textContent=`Enter ${nearby.name}`}else{nearbyCard.hidden=true;action.hidden=true}}
action?.addEventListener('click',()=>nearby&&startSubject(nearby.id));nearbyCard?.addEventListener('click',()=>{if(nearby){target={x:nearby.x,y:nearby.y};dismissHint()}});
function tick(now){const dt=Math.min((now-last)/1000,.05);last=now;if(target){const dx=target.x-player.x,dy=target.y-player.y,d=Math.hypot(dx,dy);if(d>.7){const sp=20;player.x+=dx/d*sp*dt;player.y+=dy/d*sp*dt}else target=null;world.player2d={x:player.x,y:player.y};if(Math.random()<.03)write(WORLD_KEY,world)}updateNearby();draw();requestAnimationFrame(tick)}requestAnimationFrame(tick);
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture?.(e.pointerId);drag={id:e.pointerId,x:e.clientX,y:e.clientY,sx:e.clientX,sy:e.clientY};target=null});
canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(e.clientX-drag.sx,e.clientY-drag.sy)>8){player.x=clamp(player.x+dx*.12/zoom,3,97);player.y=clamp(player.y+dy*.12/zoom,5,95);drag.x=e.clientX;drag.y=e.clientY;dismissHint()}});
canvas.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const moved=Math.hypot(e.clientX-drag.sx,e.clientY-drag.sy);if(moved<9){const p=worldPoint(e.clientX-canvas.getBoundingClientRect().left,e.clientY-canvas.getBoundingClientRect().top);let hit=null,hd=999;for(const [id,s] of Object.entries(SUBJECTS)){const d=dist(p,s);if(d<hd){hd=d;hit={id,...s}}}target=hd<9?{x:hit.x,y:hit.y}:{x:clamp(p.x,3,97),y:clamp(p.y,5,95)};dismissHint()}drag=null});
canvas.addEventListener('pointercancel',()=>drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=clamp(zoom-e.deltaY*.0015,.82,1.45);dismissHint()},{passive:false});
let touches=[];canvas.addEventListener('touchstart',e=>{if(e.touches.length===2){touches=[...e.touches].map(t=>({x:t.clientX,y:t.clientY}));pinch={d:Math.hypot(touches[1].x-touches[0].x,touches[1].y-touches[0].y),z:zoom}}},{passive:true});canvas.addEventListener('touchmove',e=>{if(e.touches.length===2&&pinch){const t=[...e.touches],d=Math.hypot(t[1].clientX-t[0].clientX,t[1].clientY-t[0].clientY);zoom=clamp(pinch.z*d/pinch.d,.82,1.45);dismissHint()}},{passive:true});canvas.addEventListener('touchend',()=>pinch=null,{passive:true});
function refreshHUD(){world=read(WORLD_KEY,world);const academy=read(ACADEMY_KEY,{}),xp=academy.xp||academy.totalXP||0,level=Math.max(1,Math.floor(xp/180)+1);document.querySelectorAll('#worldCoins,#shopCoins').forEach(el=>el.textContent=world.coins||0);const lv=document.getElementById('worldLevel');if(lv)lv.textContent=level}setInterval(refreshHUD,800);refreshHUD();
function renderShop(){if(!shop)return;world=read(WORLD_KEY,world);shop.innerHTML='';BUILD_ITEMS.forEach(item=>{const owned=(world.owned||[]).includes(item.id),b=document.createElement('button');b.className='build-item'+(owned?' owned':'');b.disabled=owned||world.coins<item.cost;b.innerHTML=`<span class="build-icon">${item.icon}</span><strong>${item.name}</strong><small>${item.desc}</small><span class="cost">${owned?'✓ Built':`🪙 ${item.cost}`}</span>`;b.onclick=()=>{world=read(WORLD_KEY,world);if(world.coins<item.cost||world.owned.includes(item.id))return;world.coins-=item.cost;world.spent=(world.spent||0)+item.cost;world.owned.push(item.id);write(WORLD_KEY,world);renderShop();refreshHUD()};shop.appendChild(b)})}
document.getElementById('openBase')?.addEventListener('click',()=>{basePanel.hidden=false;renderShop()});document.getElementById('closeBase')?.addEventListener('click',()=>basePanel.hidden=true);addEventListener('storage',refreshHUD);addEventListener('ks2coins',refreshHUD);
})();